server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # API logs
  - job_name: api
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail", "com.docker.compose.service=api"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{service="api"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: message
            - labels:
                level:

  # Web logs
  - job_name: web
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail", "com.docker.compose.service=web"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com.docker.compose.service']
        target_label: 'service'
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{service="web"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: message
            - labels:
                level:

  # Agent logs
  - job_name: agent
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail", "com.docker.compose.service=agent"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com.docker.compose.service']
        target_label: 'service'
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{service="agent"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: message
            - labels:
                level:

